[backups]
include = [
    "/Users/lesterrry/Downloads/font/demo.html",
    "/Users/lesterrry/Downloads/sticker.jpg",
    "/Users/lesterrry/Downloads/font"
]
exclude = [
    "node_modules",
    "*.woff",
    "40.jpg",
    "/Users/lesterrry/Downloads/sticker.jpg"
]
output_directory = "./"

[secrets]
disk_token = "1234"
